version: '3.5'

services:
  app:
    container_name: epsor-challenge-app
    restart : always
    build: .
    depends_on:
      - mongodb
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  mongodb:
    container_name: epsor-challenge-mongo
    image : mongo
    ports:
      - '27017:27017'
    
