version: '3.5'

services:
  mongodb:
    container_name: epsor-challenge-mongo
    image : mongo
    ports:
      - '27017:27017'
  zookeeper:
    container_name: epsor-challenge-zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: epsor-challenge-kafka
    image: bitnami/kafka:2.5.0
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
    depends_on:
      - zookeeper
    
